<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-BB45DJB6" failures="1" tests="4" name="Test" time="34.037" errors="0" timestamp="2023-03-27T15:25:50 IST">
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityWithIncorrectData1" time="2.551"/>
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityWithIncorrectData2" time="1.045"/>
  <testcase classname="test_Package.LogIn" name="VerifyLoginPage" time="0.0">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test_Package.LogIn.VerifyLoginPage(LogIn.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginPage -->
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityCorrectData" time="1.892"/>
  <testcase classname="test_Package.BaseClass" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="test_Package.BaseClass" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- Test -->
