<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-BB45DJB6" failures="1" tests="1" name="Test(failed)" time="10.227" errors="0" timestamp="2023-03-20T17:17:50 IST">
  <testcase classname="test_Package.LogIn" name="VerifyLoginPage" time="0.0">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test_Package.LogIn.VerifyLoginPage(LogIn.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginPage -->
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityWithIncorrectData2" time="0.0">
    <ignored/>
  </testcase> <!-- verifyFunctionalityWithIncorrectData2 -->
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityWithIncorrectData1" time="0.0">
    <ignored/>
  </testcase> <!-- verifyFunctionalityWithIncorrectData1 -->
  <testcase classname="test_Package.LogIn" name="verifyFunctionalityCorrectData" time="0.0">
    <ignored/>
  </testcase> <!-- verifyFunctionalityCorrectData -->
</testsuite> <!-- Test(failed) -->
